name: Subgraph Query Match Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-query-match:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # 3️⃣ Install PyTorch + PyG CPU and dependencies
      - name: Install PyTorch, PyG, and other dependencies
        run: |
          python -m pip install --upgrade pip
          # Install PyTorch CPU
          pip install torch==2.4.1+cpu torchvision==0.19.1+cpu torchaudio==2.4.1+cpu --index-url https://download.pytorch.org/whl/cpu
          # Install PyG CPU wheels
          pip install torch-scatter -f https://data.pyg.org/whl/torch-2.4.1+cpu.html
          pip install torch-sparse -f https://data.pyg.org/whl/torch-2.4.1+cpu.html
          pip install torch-cluster -f https://data.pyg.org/whl/torch-2.4.1+cpu.html
          pip install torch-spline-conv -f https://data.pyg.org/whl/torch-2.4.1+cpu.html
          # Install PyG main package and other Python packages
          pip install torch-geometric deepsnap networkx matplotlib tqdm

      # 4️⃣ Prepare output directories
      - name: Prepare output directories
        run: |
          mkdir -p results
          mkdir -p plots

      # 5️⃣ Run Query_match.py with pretrained model and example graphs
      - name: Run Query Match
        run: |
          python Query_match.py \
            --query_path examples/query_graph.pkl \
            --target_path examples/target_graph.pkl \
            --model_path ckpt/model.pt \
            --output_path results/query_result.txt

      # 6️⃣ Display the subgraph match result in Actions log
      - name: Show query result
        run: |
          echo "Subgraph Query Result:"
          cat results/query_result.txt || echo "Result file not found"

      # 7️⃣ Upload results and plots as artifacts
      - name: Upload results and plots
        uses: actions/upload-artifact@v4
        with:
          name: query-match-artifacts
          path: |
            results/
            plots/
          retention-days: 7
          if-no-files-found: warn
